import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = fileURLToPath(new URL('../', import.meta.url));
const read = (name) => readFile(path.join(root, name), 'utf8');
const tokenSource = await read('vendor/tokens.css');
const themeSource = await read('vendor/slate.css');
const provenance = JSON.parse(await read('vendor/source.json'));
const tokens = Object.create(null);
function declarations(block) {
  for (const match of block.matchAll(/--(neon-[\w-]+):\s*([^;]+);/g)) tokens[match[1]] = match[2].trim();
}
const base = tokenSource.match(/:root\s*\{([^}]+)\}/);
const dark = themeSource.match(/\[data-neon-mode="dark"\][^{]*\{([^}]+)\}/);
if (!base || !dark) throw new Error('Upstream token structure changed; review the semantic mapping.');
declarations(base[1]);
declarations(dark[1]);
function resolve(name, seen = []) {
  if (!tokens[name] || seen.includes(name)) throw new Error(`Unknown/circular token ${name}`);
  const value = tokens[name].replace(/var\(--(neon-[\w-]+)\)/g, (_, ref) => resolve(ref, [...seen, name]));
  if (/var\(|color-mix\(|rgba?\(|gradient\(|env\(|min\(|max\(|[{}<>]/.test(value)) {
    throw new Error(`Token ${name} needs an explicit classic-compatible mapping: ${value}`);
  }
  return value;
}
const used = Object.create(null);
const compiled = Object.create(null);
for (const kind of ['js', 'css']) {
  let source = await read(`src/neonux-lc.${kind}`);
  // Template prose deliberately uses a non-token placeholder.
  source = source.replace(/\{\{(neon-[\w-]+)\}\}/g, (_, name) => {
    used[name] = resolve(name);
    return used[name];
  });
  if (/\{\{neon-/.test(source)) throw new Error('Uncompiled token');
  const output = `/* Generated from NeonUX ${provenance.commit}; edit src/ and run build. */\n${source}`;
  compiled[kind] = output;
  const destination = `dist/neonux-lc.${kind}`;
  if (process.argv.includes('--check')) {
    if (await read(destination) !== output) throw new Error(`Stale ${destination}; run the NeonUX-LC build.`);
  } else await writeFile(path.join(root, destination), output);
}
const mapping = JSON.stringify({ source: provenance, tokens: Object.fromEntries(Object.entries(used).sort()) }, null, 2) + '\n';
if (process.argv.includes('--check')) {
  if (await read('dist/token-map.json') !== mapping) throw new Error('Stale token-map.json');
} else await writeFile(path.join(root, 'dist/token-map.json'), mapping);

// Server modules carry the exact same generated bytes, without runtime filesystem
// resolution. This works in Node, Bun and both Next bundlers with local workspaces.
for (const [name, output] of [
  ['dist/server-assets.js', '// Generated server-only asset values; never load this module in a classic browser.\nexport const CLASSIC_CSS = ' + JSON.stringify(compiled.css) + ';\nexport const CLASSIC_JS = ' + JSON.stringify(compiled.js) + ';\n'],
  ['dist/server-assets.d.ts', 'export declare const CLASSIC_CSS: string;\nexport declare const CLASSIC_JS: string;\n']
]) {
  if (process.argv.includes('--check')) {
    if (await read(name) !== output) throw new Error('Stale '+name);
  } else await writeFile(path.join(root,name),output);
}
